services:
  - type: web
    name: secure-openai-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # set in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5-nano
